### ISSUE TITLE
Can't build with LLVM 5.0

### ISSUE THREAD

**Issue by tpgxyz** [coreutils/coreutils#11]
Hi @pixelb  @eggert ,

i can't build coreutils 8.28 with LLVM/clang 5.0.0

In file included from lib/mbsstr.c:32:
./lib/str-kmp.h:42:30: error: use of unknown builtin '__builtin_mul_overflow_p' [-Wimplicit-function-declaration]
  size_t *table = (size_t *) nmalloca (m, sizeof (size_t));
                             ^
./lib/malloca.h:79:25: note: expanded from macro 'nmalloca'
#define nmalloca(n, s) (xalloc_oversized (n, s) ? NULL : malloca ((n) * (s)))
                        ^
./lib/xalloc-oversized.h:46:4: note: expanded from macro 'xalloc_oversized'
   __builtin_mul_overflow_p (n, s, (__xalloc_count_type) 1)
   ^
1 error generated.

here are the logs
http://file-store.openmandriva.org/api/v1/file_stores/e06076e9b0c5cef8f2d26b80f37d0143023523c4.log?show=true

**Comment by eggert** [comment]
[Responding to https://github.com/coreutils/coreutils/issues/11 and 
CC'ing to bug-coreutils.]

Thanks for the heads-up. That's odd, as I just looked at the LLVM source 
code, and cfe-5.0.0.src/lib/Frontend/InitPreprocessor.cpp defines 
__GNUC__ to 4, whereas Coreutils (via Gnulib) doesn't use 
__builtin_mul_overflow_p unless __GNUC__ is at least 7.

To help debug this, what is the value of __GNUC__ on your platform? For 
example, what is the output of the following shell command?

echo __GNUC__ | /usr/bin/clang -E -

and what happens if you append this line to lib/mbsstr.c

"__GNUC__" __GNUC__

and then run this (long, one-line) command:

/usr/bin/clang -E -I. -I./lib  -Ilib -I./lib -Isrc -I./src    -Os -gdwarf-4 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4  -fPIC -flto -fPIC -D_GNU_SOURCE=1 lib/mbsstr.c >lib/mbsstr.i

and look at the last few lines of lib/mbsttr.i?


On Fedora 26, which has clang version 4.0.1 (tags/RELEASE_401/final), these commands say that __GNUC__ is 4, which is what I would expect.

Also, does the attached patch to lib/intprops.h work around the problem?

**Comment by tpgxyz** [comment]
@eggert  Hi,

here is the output form

```
[root@localhost etc]# echo __GNUC__ | /usr/bin/clang -E -
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 316 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
7
```
[root@localhost etc]# rpm -qf `which clang`
clang-5.0.0-1-omv3001.x86_64.rpm

**Comment by eggert** [comment]
Tomasz Paweł Gajc wrote:
> here is the output form
> 
> [root@localhost etc]# echo __GNUC__ | /usr/bin/clang -E -
> # 1 "<stdin>"
> # 1 "<built-in>" 1
> # 1 "<built-in>" 3
> # 316 "<built-in>" 3
> # 1 "<command line>" 1
> # 1 "<built-in>" 2
> # 1 "<stdin>" 2
> 7

Can you investigate why __GNUC__ is 7 on your platform? As I said, I looked at 
the LLVM/clang 5.0.0 source code and it sets __GNUC__ to 4.

Are you using a version of clang that uses the GNU C preprocessor? If so, that 
would explain the problem. That combination is not supported, since preprocessor 
variables must describe the compiler accurately.

Also, please try the patch to lib/intprops.h that I suggested. You can find it here:

https://lists.gnu.org/archive/html/bug-gnulib/2017-09/msg00107.html

**Comment by tpgxyz** [comment]
@berolinux Can you please help us here ?

**Comment by berolinux** [comment]
Our clang package is (intentionally) patched to return __GNUC__ == 7 because clang 5.0 is closer to gcc 7.x than to any other version of gcc (the reason why it returns 4 in unpatched clang is simple: The upstream maintainer of that particular piece of code works at a company that doesn't allow its employees to touch anything GPLv3, so the last version of gcc he can look at is 4.9).

Unfortunately there's no complete match possible because there is no exact match between any clang and gcc version. Returning 4 (or 5 or 6) misses a number of possible optimizations where code checks for a compiler feature using the __GNUC__ version, and sometimes even causes code not to compile
#if __GNUC__ <= 4
/* Some broken code that works around an incomplete implementation of C11 or so */
#else
/* Right thing to do */
#endif
But 7 goes wrong when it's used to check for __builtin_mul_overflow_p and possibly a few other builtins.

The best fix is to check for __builtin_mul_overflow_p in configure.ac, CMakeLists.txt or friends instead of assuming that anything that claims to be __GNUC__ >= 7 has __builtin_mul_overflow_p (this is also better for pure gcc -- after all gcc 9 or 10 might remove or rename a builtin that is present in 7).

The proposed intprops.h fix does the trick, but isn't a very good solution either (clang 6 or 7 might implement __builtin_mul_overflow_p and then miss out on it).

Clang provides a useful __has_builtin macro (that seems to be on its way towards being implemented in gcc as well, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66970 ), so one solution could be

#if __GNUC__ >= 7 && (!defined(__clang__) || __has_builtin(__builtin_mul_overflow_p))

But that can get rather long and will still work only for gcc and clang (not any compiler that might come out of nowhere in the future)

**Comment by berolinux** [comment]
This works for me with both clang 5.0 and gcc 7.2:

[coreutils-8.28-check-for-__builtin_mul_overflow_p.patch.txt](https://github.com/coreutils/coreutils/files/1427998/coreutils-8.28-check-for-__builtin_mul_overflow_p.patch.txt)

**Comment by timofonic** [comment]
@berolinux Any upstream merge plans?

**Comment by tpgxyz** [comment]
@eggert WDYT about @berolinux patch and merging it into codebase?

**Comment by eggert** [comment]
As I've written [elsewhere](http://lists.gnu.org/r/bug-gnulib/2017-10/msg00107.html), I'm not wild about this patch. As I understand it, GNU programs like Coreutils build just fine with LLVM 5.0. The problem is not with LLVM 5.0: the problem is with patching LLVM 5.0 to make it pretend that it is compatible with GCC 7, which it is not.

I don't understand why it's helpful to patch LLVM 5.0 that way. Perhaps it is so that some programs run faster when built with clang? If so, I suggest compiling those programs with 'clang -U__GNUC__ -D__GNUC__=7' and then reverting the patch to LLVM 5.0. Or if that's too much trouble, you can compile coreutils and other GNU programs with 'gcc' or with 'clang -U__GNUC__ -D__GNUC__=4'.

If GCC starts supporting __has_builtin I would like to change intprops.h to use __has_builtin, which would be another way to address the problem. I haven't seen much progress lately on that front, though.

**Comment by agordon** [comment]
Latest coreutils builds fine with clang-8. clang-7. clang-6.0 and clang-5.0 on Debian 9.8/amd64 - as such I'm closing this bug.

For other issues, please *do not* use github issues - instead send an email to coreutils@gnu.org.
